fix: fix issue rendering full width on mobile
1hanzla100/developer-portfolio pull request #10
Opened 2022-01-10 15:00 UTC by bobbyg603

On mobile devices, the layout wasn't rendering the full width. The fix seems to be to set the scaling factor of the viewport to a constant value of 1. Here's the before and after:

<img width="1680" alt="image" src="https://user-images.githubusercontent.com/2646053/148787450-2a6733e4-0bc7-45cb-9832-1891b356d068.png">

2022-01-10 17:49 UTC, 1hanzla100 commented
@bobbyg603 There is no issue in mobile vie
![Capture](https://user-images.githubusercontent.com/59178380/148813929-d5ee7fdd-5ede-471b-8775-bfa92e8768b1.PNG)
w

2022-01-10 18:34 UTC, bobbyg603 commented
@1hanzla100 after further review, I think this might happen when one of the headers is long enough to extend off the screen. overflow hidden might be a more appropriate fix. I'll fiddle around with this some more and see if I can give you more information.

2022-01-12 01:25 UTC, bobbyg603 commented
@1hanzla100 force pushed a better fix, here's a comparison of localhost and the version you're hosting

![image](https://user-images.githubusercontent.com/2646053/149047393-ac882079-7715-41a3-8103-6328a99f8674.png)

2022-01-12 17:11 UTC, 1hanzla100 requested changes
@bobbyg603 Remove the duplicate import import of CSS files `argon-design-system-react.css` & `font-awesome.min.css`

2022-01-12 17:17 UTC, bobbyg603 commented
> @bobbyg603 Remove the duplicate import import of CSS files `argon-design-system-react.css` & `font-awesome.min.css`

good catch, my mistake, this was the result of a hasty git cherry-pick 🤦. this has been fixed

2022-01-12 17:43 UTC, 1hanzla100 approved these changes

2022-01-12 17:45 UTC, merged